impl_libs =
import intf_libs = libsimpleble%lib{simpleble}

example_dirs = \
    connect \
    list_adapters \
    notify \
    notify_multi \
    read \
    scan \
    write

for example: $example_dirs
{
    exe{$(example)_example}: {hxx cxx}{$example/* common/*}
    exe{$(example)_example}: $intf_libs
    ./: exe{$(example)_example}
}
