import libs = libsimplebluez%lib{simplebluez}

example_dirs = \
    ble_nus \
    connect \
    list_adapters \
    list_paired \
    notify \
    pair \
    read \
    scan

for example: $example_dirs
{
    exe{$(example)_example}: cxx{$example/*}
    exe{$(example)_example}: $libs
    ./: exe{$(example)_example}
}
