
#ifndef SIMPLEBLE_EXPORT_H
#define SIMPLEBLE_EXPORT_H

#if !defined(SIMPLEBLE_STATIC) && defined(_WIN32)
#ifdef SIMPLEBLE_EXPORTS
#define SIMPLEBLE_EXPORT __declspec(dllexport)
#else
#define SIMPLEBLE_EXPORT __declspec(dllimport)
#endif
#else
#define SIMPLEBLE_EXPORT
#endif

#ifndef SIMPLEBLE_NO_EXPORT
#define SIMPLEBLE_NO_EXPORT
#endif

#ifndef SIMPLEBLE_DEPRECATED
#define SIMPLEBLE_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SIMPLEBLE_DEPRECATED_EXPORT
#define SIMPLEBLE_DEPRECATED_EXPORT SIMPLEBLE_EXPORT SIMPLEBLE_DEPRECATED
#endif

#ifndef SIMPLEBLE_DEPRECATED_NO_EXPORT
#define SIMPLEBLE_DEPRECATED_NO_EXPORT SIMPLEBLE_NO_EXPORT SIMPLEBLE_DEPRECATED
#endif

#endif /* SIMPLEBLE_EXPORT_H */
