import intf_libs = libsimpleble%lib{simpleble}

example_dirs = \
    connect \
    connect_safe \
    list_adapters \
    notify \
    notify_multi \
    read \
    scan \
    write

lib{common}: {cxx hxx}{common/*}
lib{common}: $intf_libs

for example: $example_dirs
{
    exe{$(example)_example}: cxx{$example/*}
    exe{$(example)_example}: $intf_libs lib{common}
    ./: exe{$(example)_example}
}
