import libs = libsimpleble%lib{simpleble}

example_dirs = \
    connect \
    connect_safe \
    list_adapters \
    notify \
    notify_multi \
    read \
    scan \
    write

for example: $example_dirs
{
    exe{$(example)_example}: cxx{$example/*} {cxx hxx}{common/*}
    exe{$(example)_example}: $libs
    ./: exe{$(example)_example}
}

# select some specific examples as test which do not require
# user-interaction
exe{list_adapters_example}: test = true
