import impl_libs = fmt%lib{fmt}

# Public headers.
pub = [dir_path] ../include/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{simpledbus}: $pub/{$pub_hdrs}
lib{simpledbus}: {hxx cxx}{**}
lib{simpledbus}: $impl_libs

# Build options.
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

src_dirs = {**/}
for d: $src_dirs
{
    cxx.poptions +=  "-I$out_pfx_src/$d" "-I$src_pfx_src/$d"
}

cxx.poptions += "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc" \
                "-DSIMPLEDBUS_LOG_LEVEL=$config.libsimpledbus.log_level"
cxx.libs += $platform_libs

# Export options.
lib{simpledbus}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
if $version.pre_release
  lib{simpledbus}: bin.lib.version = "-$version.project_id"
else
  lib{simpledbus}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
{hxx ixx}{*}: install = false
